-- Create composers table
CREATE TABLE IF NOT EXISTS composers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR NOT NULL,
  birth_year INTEGER,
  death_year INTEGER,
  nationality VARCHAR,
  period VARCHAR,
  bio TEXT,
  image_url VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add foreign key to pieces table
ALTER TABLE pieces ADD COLUMN IF NOT EXISTS composer_id UUID REFERENCES composers(id);

-- Add composers data
INSERT INTO composers (name, birth_year, death_year, nationality, period, bio, image_url) VALUES
('Johann Sebastian Bach', 1685, 1750, 'German', 'Baroque', 'Johann Sebastian Bach was a German composer and musician of the Baroque period. He is known for instrumental compositions such as the Brandenburg Concertos and the Goldberg Variations, and for vocal music such as the St Matthew Passion and the Mass in B minor.', 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=400&q=80'),
('Wolfgang Amadeus Mozart', 1756, 1791, 'Austrian', 'Classical', 'Wolfgang Amadeus Mozart, baptised as Johannes Chrysostomus Wolfgangus Theophilus Mozart, was a prolific and influential composer of the Classical period. Born in Salzburg, Mozart showed prodigious ability from his earliest childhood.', 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&q=80'),
('Ludwig van Beethoven', 1770, 1827, 'German', 'Classical/Romantic', 'Ludwig van Beethoven was a German composer and pianist. Beethoven remains one of the most admired composers in the history of Western music; his works rank amongst the most performed of the classical music repertoire.', 'https://images.unsplash.com/photo-1558584673-c834fb1cc3ca?w=400&q=80'),
('Frédéric Chopin', 1810, 1849, 'Polish', 'Romantic', 'Frédéric François Chopin was a Polish composer and virtuoso pianist of the Romantic era who wrote primarily for solo piano. He has maintained worldwide renown as a leading musician of his era.', 'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=400&q=80'),
('Franz Schubert', 1797, 1828, 'Austrian', 'Romantic', 'Franz Peter Schubert was an Austrian composer of the late Classical and early Romantic eras. Despite his short lifetime, Schubert left behind a vast oeuvre, including more than 600 secular vocal works, seven complete symphonies, sacred music, operas, incidental music and a large body of piano and chamber music.', 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=400&q=80'),
('Claude Debussy', 1862, 1918, 'French', 'Impressionist', 'Achille-Claude Debussy was a French composer. He is sometimes seen as the first Impressionist composer, although he vigorously rejected the term. He was among the most influential composers of the late 19th and early 20th centuries.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Erik Satie', 1866, 1925, 'French', 'Early Modern', 'Éric Alfred Leslie Satie, who signed his name Erik Satie after 1884, was a French composer and pianist. Satie was an influential artist in the late 19th- and early 20th-century Parisian avant-garde.', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('Franz Liszt', 1811, 1886, 'Hungarian', 'Romantic', 'Franz Liszt was a Hungarian composer, virtuoso pianist, conductor, music teacher, arranger, and organist of the Romantic era. He was also a writer, a philanthropist, a Hungarian nationalist and a Franciscan tertiary.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Felix Mendelssohn', 1809, 1847, 'German', 'Romantic', 'Jakob Ludwig Felix Mendelssohn Bartholdy, born and widely known as Felix Mendelssohn, was a German composer, pianist, organist and conductor of the early Romantic period.', 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=400&q=80'),
('Robert Schumann', 1810, 1856, 'German', 'Romantic', 'Robert Schumann was a German composer, pianist, and influential music critic. He is widely regarded as one of the greatest composers of the Romantic era.', 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&q=80'),
('Sergei Rachmaninoff', 1873, 1943, 'Russian', 'Romantic', 'Sergei Vasilyevich Rachmaninoff was a Russian composer, virtuoso pianist, and conductor of the late Romantic period. The influence of Tchaikovsky, Rimsky-Korsakov, Balakirev, Mussorgsky, and other Russian composers is seen in his early works.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Scott Joplin', 1868, 1917, 'American', 'Ragtime', 'Scott Joplin was an American composer and pianist. Joplin achieved fame for his ragtime compositions and was dubbed the "King of Ragtime". During his brief career, he wrote over 100 original ragtime pieces, one ragtime ballet, and two operas.', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('Carl Philipp Emanuel Bach', 1714, 1788, 'German', 'Classical', 'Carl Philipp Emanuel Bach was a German Classical period musician and composer, the fifth child and second surviving son of Johann Sebastian Bach and Maria Barbara Bach. His second name was given in honor of his godfather Georg Philipp Telemann, a friend of Johann Sebastian Bach.', 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=400&q=80'),
('Muzio Clementi', 1752, 1832, 'Italian', 'Classical', 'Muzio Filippo Vincenzo Francesco Saverio Clementi was an Italian composer, pianist, pedagogue, conductor, music publisher, editor, and piano manufacturer who was mostly active in England.', 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&q=80'),
('Albert Pieczonka', 1828, 1912, 'Polish', 'Romantic', 'Albert Pieczonka was a Polish composer and pianist. He is best known for his piano piece "Tarantella in A minor".', 'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=400&q=80'),
('Christian Sinding', 1856, 1941, 'Norwegian', 'Romantic', 'Christian August Sinding was a Norwegian composer. He is best known for his lyrical work for piano, "Frühlingsrauschen" (Rustle of Spring, 1896).', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Edward MacDowell', 1860, 1908, 'American', 'Romantic', 'Edward Alexander MacDowell was an American composer and pianist of the late Romantic period. He was best known for his second piano concerto and his piano suites Woodland Sketches, Sea Pieces, and New England Idylls.', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('Pyotr Ilyich Tchaikovsky', 1840, 1893, 'Russian', 'Romantic', 'Pyotr Ilyich Tchaikovsky was a Russian composer of the Romantic period. He was the first Russian composer whose music made a lasting impression internationally. He was honored in 1884 by Tsar Alexander III and awarded a lifetime pension.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Nikolai Rimsky-Korsakov', 1844, 1908, 'Russian', 'Romantic', 'Nikolai Andreyevich Rimsky-Korsakov was a Russian composer, and a member of the group of composers known as The Five. He was a master of orchestration and his best-known orchestral compositions include Capriccio Espagnol, the Russian Easter Festival Overture, and the symphonic suite Scheherazade.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('George Gershwin', 1898, 1937, 'American', 'Jazz/Classical Fusion', 'George Gershwin was an American composer and pianist whose compositions spanned both popular and classical genres. Among his best-known works are the orchestral compositions Rhapsody in Blue and An American in Paris, the songs Swanee and Fascinating Rhythm, and the opera Porgy and Bess.', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('Johannes Brahms', 1833, 1897, 'German', 'Romantic', 'Johannes Brahms was a German composer, pianist, and conductor of the Romantic period. Born in Hamburg into a Lutheran family, Brahms spent much of his professional life in Vienna. Brahms has been considered, by his contemporaries and by later writers, as both a traditionalist and an innovator.', 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=400&q=80'),
('Franz Joseph Haydn', 1732, 1809, 'Austrian', 'Classical', 'Franz Joseph Haydn was an Austrian composer of the Classical period. He was instrumental in the development of chamber music such as the piano trio. His contributions to musical form have earned him the epithets "Father of the Symphony" and "Father of the String Quartet".', 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&q=80'),
('Antonio Vivaldi', 1678, 1741, 'Italian', 'Baroque', 'Antonio Lucio Vivaldi was an Italian Baroque composer, virtuoso violinist, teacher, impresario, and Roman Catholic priest. Born in Venice, the capital of the Venetian Republic, Vivaldi is regarded as one of the greatest Baroque composers, and his influence during his lifetime was widespread across Europe.', 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&q=80'),
('George Frideric Handel', 1685, 1759, 'German-British', 'Baroque', 'George Frideric Handel was a German-British Baroque composer well known for his operas, oratorios, anthems, concerti grossi and organ concertos. Handel received his training in Halle and worked as a composer in Hamburg and Italy before settling in London in 1712, where he spent the bulk of his career.', 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=400&q=80'),
('Domenico Scarlatti', 1685, 1757, 'Italian', 'Baroque', 'Giuseppe Domenico Scarlatti was an Italian composer. He is classified primarily as a Baroque composer chronologically, although his music was influential in the development of the Classical style and he was one of the few Baroque composers to transition into the Classical period.', 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&q=80'),
('Maurice Ravel', 1875, 1937, 'French', 'Impressionist', 'Joseph Maurice Ravel was a French composer, pianist and conductor. He is often associated with impressionism along with his elder contemporary Claude Debussy, although both composers rejected the term. In the 1920s and 1930s Ravel was internationally regarded as France''s greatest living composer.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Dmitri Shostakovich', 1906, 1975, 'Russian', 'Modern', 'Dmitri Dmitriyevich Shostakovich was a Russian composer and pianist. He is regarded as one of the major composers of the 20th century, with a unique harmonic language and a historic importance due to his years of work under Stalin.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Béla Bartók', 1881, 1945, 'Hungarian', 'Modern', 'Béla Viktor János Bartók was a Hungarian composer, pianist, and ethnomusicologist. He is considered one of the most important composers of the 20th century; he and Franz Liszt are regarded as Hungary''s greatest composers.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Igor Stravinsky', 1882, 1971, 'Russian', 'Modern', 'Igor Fyodorovich Stravinsky was a Russian composer, pianist, and conductor. He is widely considered one of the most important and influential composers of the 20th century.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Sergei Prokofiev', 1891, 1953, 'Russian', 'Modern', 'Sergei Sergeyevich Prokofiev was a Russian Soviet composer, pianist and conductor. As the creator of acknowledged masterpieces across numerous music genres, he is regarded as one of the major composers of the 20th century.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Aaron Copland', 1900, 1990, 'American', 'Modern', 'Aaron Copland was an American composer, composition teacher, writer, and later a conductor of his own and other American music. Copland was referred to by his peers and critics as "the Dean of American Composers".', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('Philip Glass', 1937, NULL, 'American', 'Minimalist', 'Philip Glass is an American composer and pianist. He is widely regarded as one of the most influential composers of the late 20th century. Glass''s work has been associated with minimalism, being built up from repetitive phrases and shifting layers.', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('John Cage', 1912, 1992, 'American', 'Avant-garde', 'John Milton Cage Jr. was an American composer, music theorist, artist, and philosopher. A pioneer of indeterminacy in music, electroacoustic music, and non-standard use of musical instruments, Cage was one of the leading figures of the post-war avant-garde.', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('Arvo Pärt', 1935, NULL, 'Estonian', 'Minimalist', 'Arvo Pärt is an Estonian composer of classical and religious music. Since the late 1970s, Pärt has worked in a minimalist style that employs his self-invented compositional technique, tintinnabuli.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Einojuhani Rautavaara', 1928, 2016, 'Finnish', 'Modern', 'Einojuhani Rautavaara was a Finnish composer of classical music. He is among the most notable Finnish composers after Jean Sibelius.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Jean Sibelius', 1865, 1957, 'Finnish', 'Romantic/Modern', 'Jean Sibelius was a Finnish composer and violinist of the late Romantic and early-modern periods. He is widely recognized as his country''s greatest composer and, through his music, is often credited with having helped Finland to develop a national identity during its struggle for independence from Russia.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Edvard Grieg', 1843, 1907, 'Norwegian', 'Romantic', 'Edvard Hagerup Grieg was a Norwegian composer and pianist. He is widely considered one of the leading Romantic era composers, and his music is part of the standard classical repertoire worldwide.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Antonín Dvořák', 1841, 1904, 'Czech', 'Romantic', 'Antonín Leopold Dvořák was a Czech composer, one of the first to achieve worldwide recognition. Following the Romantic-era nationalist example of his predecessor Bedřich Smetana, Dvořák frequently employed rhythms and other aspects of the folk music of Moravia and his native Bohemia.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Camille Saint-Saëns', 1835, 1921, 'French', 'Romantic', 'Charles-Camille Saint-Saëns was a French composer, organist, conductor and pianist of the Romantic era. His best-known works include Introduction and Rondo Capriccioso, the Second Piano Concerto, the First Cello Concerto, Danse macabre, the opera Samson and Delilah, the Third Violin Concerto, the Third ("Organ") Symphony, and The Carnival of the Animals.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Gabriel Fauré', 1845, 1924, 'French', 'Romantic', 'Gabriel Urbain Fauré was a French composer, organist, pianist and teacher. He was one of the foremost French composers of his generation, and his musical style influenced many 20th-century composers.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('César Franck', 1822, 1890, 'Belgian-French', 'Romantic', 'César-Auguste-Jean-Guillaume-Hubert Franck was a composer, pianist, organist, and music teacher who worked in Paris during his adult life. He was born in Liège, Belgium, but after 1830 he lived in Paris, where he was naturalized as a French citizen.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80'),
('Isaac Albéniz', 1860, 1909, 'Spanish', 'Romantic', 'Isaac Manuel Francisco Albéniz y Pascual was a Spanish virtuoso pianist, composer, and conductor. He is one of the foremost composers of the Spanish nationalist school of musicians.', 'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=400&q=80'),
('Enrique Granados', 1867, 1916, 'Spanish', 'Romantic', 'Enrique Granados y Campiña was a Spanish pianist and composer of classical music. His music is in a uniquely Spanish style and, as such, is representative of musical nationalism.', 'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=400&q=80'),
('Manuel de Falla', 1876, 1946, 'Spanish', 'Modern', 'Manuel de Falla y Matheu was a Spanish composer. Along with Isaac Albéniz, Francisco Tárrega, and Enrique Granados, he was one of Spain''s most important musicians of the first half of the 20th century.', 'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=400&q=80'),
('Joaquín Rodrigo', 1901, 1999, 'Spanish', 'Modern', 'Joaquín Rodrigo Vidre, 1st Marquis of the Gardens of Aranjuez, was a Spanish composer and a virtuoso pianist. Despite being blind from an early age, he achieved great success. Rodrigo''s music is among the most popular music of the 20th century.', 'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=400&q=80'),
('Heitor Villa-Lobos', 1887, 1959, 'Brazilian', 'Modern', 'Heitor Villa-Lobos was a Brazilian composer, conductor, cellist, pianist, and guitarist described as "the single most significant creative figure in 20th-century Brazilian art music".', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('Alberto Ginastera', 1916, 1983, 'Argentine', 'Modern', 'Alberto Evaristo Ginastera was an Argentine composer of classical music. He is considered one of the most important 20th-century classical composers of the Americas.', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80'),
('Astor Piazzolla', 1921, 1992, 'Argentine', 'Modern', 'Astor Pantaleón Piazzolla was an Argentine tango composer, bandoneon player, and arranger. His works revolutionized the traditional tango into a new style termed nuevo tango, incorporating elements from jazz and classical music.', 'https://images.unsplash.com/photo-1514119412350-e174d90d280e?w=400&q=80');

-- Update pieces table to link to composers
UPDATE pieces SET composer_id = (SELECT id FROM composers WHERE name = pieces.composer LIMIT 1);

alter publication supabase_realtime add table composers;
